server:
  port: 8888



## 配置待生成数据库文档的信息
project:
  ## 项目名称
  name: 洛伊
  database-name: scs_config


spring:
  ## 配置数据库的连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ## 注意：这里的information_schema不能修改
    url: jdbc:mysql://127.0.0.1:3306/information_schema?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456


  ## freemarker配置
  freemarker:
    #指定HttpServletRequest的属性是否可以覆盖controller的model的同名项
    allow-request-override: false
    #req访问request
    request-context-attribute: request
    #后缀名freemarker默认后缀为.ftl，当然你也可以改成自己习惯的.html
    suffix: .html

    #设置响应的内容类型
    content-type: text/html;charset=utf-8
    #是否允许mvc使用freemarker
    enabled: true
    #是否开启template caching
    cache: false
    #设定模板的加载路径，多个以逗号分隔，默认: [“classpath:/templates/”]
    template-loader-path: classpath:/templates/
    #设定Template的编码
    charset: UTF-8

mybatis:
  mapper-locations: classpath:/mapper/*/*Mapper.xml,classpath:/mapper/*Mapper.xml